#!/bin/sh

## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

VERSION="${1}"
COMMIT="${2}"

TAG="$(echo ${VERSION} | sed -e 's|~|_|g')"

git tag -s -f -m "Tagging upstream version ${VERSION}." upstream/${TAG} ${COMMIT}
