#!/bin/sh

## Copyright (C) 2006-2014 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

_MODE="$(basename ${0} | sed -e 's|^git-||' -e 's|-add$||')"

if [ -n "${1}" ]
then
	_VERSION="${1}"
else
	_VERSION="$(dpkg-parsechangelog | awk '/^Version: / { print $2 }' | cut -d: -f 2-)"
fi

_HASH="${2}"

git add . -A

chmod 0755 debian/rules

git commit -s -S -m "Adding ${_MODE} version ${_VERSION}."
git-${_MODE}-tag ${_VERSION} ${_HASH}
