#!/bin/sh

## Copyright (C) 2006-2012 Daniel Baumann <daniel.baumann@progress-technologies.net>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

_MODE="$(basename ${0} | sed -e 's|^git-||' -e 's|-[a-z]$||')"

if [ -n "${1}" ]
then
	_VERSION="${1}"
else
	_VERSION="$(dpkg-parsechangelog | awk '/^Version: / { print $2 }' | cut -d: -f 2-)"
fi

_TAG="$(echo ${_VERSION} | sed -e 's|~|_|g')"

_HASH="${2}"

if [ ! -d .git ]
then
	if ls .git* > /dev/null 2>&1
	then
		echo "W: '$(basename ${PWD})' - Not a Git repository but contains Git meta data."
	fi

	git init --shared
fi

git add .

chmod 0755 debian/rules

git commit -a -m "Adding ${_MODE} version ${_VERSION}."
git-${_MODE}-tag ${_TAG} ${_HASH}
