#!/bin/sh

## Copyright (C) 2006-2012 Daniel Baumann <daniel.baumann@progress-technologies.net>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

VERSION="${1}"
COMMIT="${2}"

TAG="$(echo ${VERSION} | sed -e 's|~|_|g')"

git tag -a -f -m "Tagging upstream version ${VERSION}." upstream/${TAG} ${COMMIT}
