.\" git-stuff(7) - additional Git utilities
.\" Copyright (C) 2006-2011 Daniel Baumann <daniel.baumann@progress-technologies.net>
.\"
.\" git-stuff comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH GIT\-STUFF 1 2011\-11\-23 9 "Git Stuff"

.SH NAME
\fBgit\-amend\-all\fR \- add and amend everything to last commit

.SH SYNOPSIS
\fBgit\-amend\-all\fR

.SH DESCRIPTION
\fBgit\-amend\-all\fR is a program that adds all untracked files and amends all changes to the last commit.

.SH OPTIONS
git\-amend\-all has no options.

.SH SEE ALSO
\fIgit\fR(1)
.PP
\fIgit\-stuff\fR(7)
.PP
This program is a part of git\-stuff.

.SH BUGS
Bugs can be reported by submitting a bugreport for the git\-stuff package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the author.

.SH AUTHOR
git\-stuff was written by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>.
