.\" git-stuff(7) - additional Git utilities
.\" Copyright (C) 2006-2013 Daniel Baumann <mail@daniel-baumann.ch>
.\"
.\" git-stuff comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
.\" This is free software, and you are welcome to redistribute it
.\" under certain conditions; see COPYING for details.
.\"
.\"
.TH GIT\-STUFF 1 2014\-01\-13 20-1 "Git Stuff"

.SH NAME
\fBgit\-debian\-add\fR \- creates a new commit and tag with all untracked files and changes as new debian version

.SH SYNOPSIS
\fBgit\-debian\-add\fR [\fIVERSION\fR]

.SH DESCRIPTION
\fBgit\-debian\-add\fR is a program that creates a new commit and tag with all untracked files and changes as a new debian version using the commit message 'Adding debian version \fIVERSION\fR.' and 'Tagging debian version \fIVERSION\fR.'. If no version is specified, \fIVERSION\fR is automatically replaced with the newest version entry (without epoche) from debian/changelog.

.SH OPTIONS
.IP "\fIVERSION\fR" 4
git\-debian\-add uses dpkg-parsechangelog from the dpkg-dev package to automatically determine the debian version to be added. This can be overridden by manually specifying the version as first argument.

.SH SEE ALSO
\fIgit\fR(1)
.PP
\fIgit\-stuff\fR(7)
.PP
This program is a part of git\-stuff.

.SH BUGS
Bugs can be reported by submitting a bugreport for the git\-stuff package in the Debian Bug Tracking System at <\fIhttp://bugs.debian.org/\fR> or by writing a mail to the author.

.SH AUTHOR
git\-stuff was written by Daniel Baumann <\fImail@daniel-baumann.ch\fR>.
